### ISSUE TITLE
Error when adding Sekizai

### ISSUE THREAD

**Issue by MERP-Solutions** [django-cms/django-sekizai#104]
When doing a fresh install of django-cms all works fine, untill I enable Sekizai. Then I get this error:

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/websites/fl/flvenv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/websites/fl/flvenv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/websites/fl/flvenv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/websites/fl/flvenv/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/websites/fl/flvenv/lib/python3.8/site-packages/django/apps/config.py", line 228, in create
    if not issubclass(app_config_class, AppConfig):
TypeError: issubclass() arg 1 must be a class
```

**Comment by marksweb** [comment]
Closing this as it requires the definition of `INSTALLED_APPS` to investigate a possible cause.
